# Generated by Django 3.0.5 on 2020-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('confirmed', models.CharField(max_length=200)),
                ('active', models.CharField(max_length=200)),
                ('discharged', models.CharField(max_length=200)),
                ('death', models.CharField(max_length=200)),
            ],
        ),
    ]
