# Generated by Django 3.0.5 on 2020-05-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states_affected', models.CharField(max_length=200)),
                ('lab_confirmed', models.CharField(max_length=200)),
                ('admitted', models.CharField(max_length=200)),
                ('discharged', models.CharField(max_length=200)),
                ('death', models.CharField(max_length=200)),
            ],
        ),
    ]
